### PR TITLE
Add colors for extension of Elixir-lang files

### PR DESCRIPTION
**Pull request by MaraniMatias**
Add colors for extension of Elixir-lang files
The extensions are '.ex' and '.exs'

### CODE REVIEW

**Comment by tiagofumo** [comment]
Hi @MaraniMatias,

so the idea for the extensions added by default is that it will match the default icons of [vim-devicons](https://github.com/ryanoasis/vim-devicons) (and [nerdfonts](https://github.com/ryanoasis/nerd-fonts)). But I can't seem to find the Elixir-lang icons in there, did you find them in vim-devicons? If yes, which Unicode value are you using for it?

I am avoiding adding too many extensions by default because it makes the plugin slower, by running many `syntax match` commands. But if you want to add your custom configuration you can add them setting the global variables in your .vimrc like it's explained in the [configuration section](https://github.com/tiagofumo/vim-nerdtree-syntax-highlight#configuration) on the README.

Thanks for opening the pull request.

**Comment by MaraniMatias** [comment]
Hi, Elixir's icon is [http://elixir-lang.org/images/logo/logo.png](http://elixir-lang.org/images/logo/logo.png).
I don't found Elixir's icon, but it like this e73f, or you can using e7c1 because Elixir compile Erlang

**Comment by tiagofumo** [comment]
@MaraniMatias I see. But like I said vim-devicons do not configure these extensions by default, and there are a lot of people complaining about lag, specially using GVim or windows 10. So I am trying to avoid adding new file extensions by default, and allow each user customize its own environment with ease using the `g:NERDTreeExtensionHighlightColor`,` g:NERDTreeSyntaxEnabledExtensions` and the other global variables, as explained in the [README](https://github.com/tiagofumo/vim-nerdtree-syntax-highlight#configuration) page.

So I thank you for contributing but for these reasons I will have to deny this pull request. 

Thanks again.

**Comment by ngscheurich** [comment]
Hey, @MaraniMatias, did the patch you submitted work for you locally? I tried to do essentially the exact same thing with a local fork (add the extensions and colors to `s:file_extension_colors` and the extensions to `s:enabled_extensions`) but couldn't get it to work. After trying various permutations of the aforementioned changes I am still unable to get it working. 😞 

@tiagofumo I tried configuring the plugin and seem to be missing something. Can you have a look at the attached screenshot and see if there is something I am obviously doing wrong?

python3_6

**Comment by alexparker** [comment]
👍  What's the right way to add this in? Add Pattern Match for .ex and .exs??

**Pull request closed without merging**
